name: "Bulk GitHub Repository Sync"
description: "🔄 Sync GitHub repositories between organizations with visibility control, Actions management, and archiving"

branding:
  icon: "git-branch"
  color: "blue"

inputs:
  repo-list-file:
    description: "YAML file containing repository mappings with source, target, visibility, and sync options"
    required: true
  source-github-token:
    description: "GitHub Personal Access Token for accessing source repositories"
    required: true
  target-github-token:
    description: "GitHub Personal Access Token for creating/updating target repositories"
    required: false
  source-github-url:
    description: "Source GitHub server URL  (for GitHub Enterprise Server, usually like https://ghes.domain.com)"
    required: false
    default: "${{ github.server_url }}"
  source-github-api-url:
    description: "Source GitHub API URL (for GitHub Enterprise Server, usually like: https://ghes.domain.com/api/v3)"
    required: false
    default: "${{ github.api_url }}"
  target-github-url:
    description: "Target GitHub server URL (for GitHub Enterprise Server, usually like https://ghes.domain.com)"
    required: false
    default: "${{ github.server_url }}"
  target-github-api-url:
    description: "Target GitHub API URL (for GitHub Enterprise Server, usually like: https://ghes.domain.com/api/v3)"
    required: false
    default: "${{ github.api_url }}"
  overwrite-repo-visibility:
    description: "Overwrite visibility of existing repositories to match YAML config"
    required: false
    default: "false"
  force-push:
    description: "Force push to target repositories (overwrites history)"
    required: false
    default: "false"

runs:
  using: "node20"
  main: "dist/index.js"
